import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#d4e4fa",
        "primary-container": "#00e5ff",
        "on-secondary-container": "#725f00",
        "on-primary-container": "#00626e",
        "surface-container-high": "#1c2b3c",
        "outline-variant": "#3b494c",
        "on-primary-fixed": "#001f24",
        "surface-container-lowest": "#010f1f",
        "secondary-fixed": "#ffe16d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#544600",
        "on-secondary-fixed": "#221b00",
        surface: "#051424",
        background: "#051424",
        "tertiary-fixed": "#dbe2f8",
        "tertiary-container": "#c8d0e6",
        "on-surface-variant": "#bac9cc",
        "secondary-fixed-dim": "#e9c400",
        "on-primary-fixed-variant": "#004f58",
        "on-surface": "#d4e4fa",
        "on-tertiary-fixed-variant": "#3f4758",
        "surface-bright": "#2c3a4c",
        "surface-dim": "#051424",
        "on-primary": "#00363d",
        "primary-fixed": "#9cf0ff",
        "secondary-container": "#ffdb3c",
        "on-error-container": "#ffdad6",
        "tertiary": "#e6ecff",
        outline: "#849396",
        "on-tertiary": "#283041",
        "surface-container": "#122131",
        "primary-fixed-dim": "#00daf3",
        "on-secondary": "#3a3000",
        "inverse-on-surface": "#233143",
        "on-tertiary-container": "#51596b",
        "surface-tint": "#00daf3",
        "surface-container-highest": "#273647",
        "surface-container-low": "#0d1c2d",
        "tertiary-fixed-dim": "#bec6dc",
        secondary: "#fff9ef",
        "inverse-primary": "#006875",
        "inverse-surface": "#d4e4fa",
        "on-tertiary-fixed": "#131c2b",
        "surface-variant": "#273647",
        primary: "#c3f5ff",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "grid-size": "32px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "data-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "data-lg": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
