import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e6edf5",
        "primary-container": "#00d5ff",
        "on-secondary-container": "#5c4a00",
        "on-primary-container": "#00242a",
        "surface-container-high": "#172331",
        "outline-variant": "rgba(255,255,255,0.08)",
        "on-primary-fixed": "#0b1117",
        "surface-container-lowest": "#0b1117",
        "secondary-fixed": "#ffd34d",
        error: "#ff5c5c",
        "on-error": "#1f0000",
        "on-secondary-fixed-variant": "#3f3300",
        "on-secondary-fixed": "#201800",
        surface: "#0b1117",
        background: "#0b1117",
        "tertiary-fixed": "#e6edf5",
        "tertiary-container": "#cdd7e2",
        "on-surface-variant": "#9fb0c2",
        "secondary-fixed-dim": "#e4b93d",
        "on-primary-fixed-variant": "#00383f",
        "on-surface": "#e6edf5",
        "on-tertiary-fixed-variant": "#3a4452",
        "surface-bright": "#1a2736",
        "surface-dim": "#0b1117",
        "on-primary": "#001f24",
        "primary-fixed": "#6fe6ff",
        "secondary-container": "#ffd34d",
        "on-error-container": "#ffd7d7",
        "tertiary": "#e6edf5",
        outline: "rgba(255,255,255,0.16)",
        "on-tertiary": "#2c3642",
        "surface-container": "#121b24",
        "primary-fixed-dim": "#00bfe3",
        "on-secondary": "#2b2200",
        "inverse-on-surface": "#0b1117",
        "on-tertiary-container": "#485261",
        "surface-tint": "#00d5ff",
        "surface-container-highest": "#1f2b3a",
        "surface-container-low": "#0f1822",
        "tertiary-fixed-dim": "#c1cbd6",
        secondary: "#fff7e6",
        "inverse-primary": "#00a7c7",
        "inverse-surface": "#e6edf5",
        "on-tertiary-fixed": "#101824",
        "surface-variant": "#1b2633",
        primary: "#b9f1ff",
        "error-container": "#4a0000",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "grid-size": "32px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-inter)", "system-ui", "sans-serif"],
        "data-sm": [
          "var(--font-jetbrains-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "monospace",
        ],
        "body-md": ["var(--font-inter)", "system-ui", "sans-serif"],
        "data-lg": [
          "var(--font-jetbrains-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "monospace",
        ],
        "label-caps": ["var(--font-inter)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "system-ui", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
