package models

import "time"

// Bar is a single OHLCV candle.
type Bar struct {
	Time   time.Time `json:"time"`
	Symbol string    `json:"symbol"`
	Open   float64   `json:"open"`
	High   float64   `json:"high"`
	Low    float64   `json:"low"`
	Close  float64   `json:"close"`
	Volume int64     `json:"volume"`
}

// Signal is a trading action.
type Signal int

const (
	SignalHold Signal = iota
	SignalBuy
	SignalSell
)

// BacktestRequest configures a backtest run with support for multiple strategies.
type BacktestRequest struct {
	Symbol       string   `json:"symbol,omitempty"`
	Symbols      []string `json:"symbols,omitempty"`
	UniverseName string   `json:"universe_name,omitempty"`
	StrategyType string   `json:"strategy_type" binding:"required"` // "MA_CROSSOVER", "KALMAN", or portfolio strategy types
	Timeframe    string   `json:"timeframe,omitempty"`              // e.g. "1Day", "1Hour"
	Feed         string   `json:"feed,omitempty"`
	Adjustment   string   `json:"adjustment,omitempty"`

	// Kalman-specific parameters
	QNoise     float64 `json:"q_noise,omitempty"`
	RNoise     float64 `json:"r_noise,omitempty"`
	ZThreshold float64 `json:"z_threshold,omitempty"`

	// MA-specific parameters
	FastPeriod  int                    `json:"fast_period,omitempty"`
	SlowPeriod  int                    `json:"slow_period,omitempty"`
	InitialCash float64                `json:"initial_cash"`
	Start       *time.Time             `json:"start,omitempty"`
	End         *time.Time             `json:"end,omitempty"`
	Parameters  map[string]interface{} `json:"parameters,omitempty"`
}

// EquityPoint is one point on the equity curve.
type EquityPoint struct {
	Time   time.Time `json:"time"`
	Equity float64   `json:"equity"`
}

// Trade is one closed entry/exit pair generated by a backtest.
type Trade struct {
	EntryTime  time.Time `json:"entry_time"`
	ExitTime   time.Time `json:"exit_time"`
	EntryPrice float64   `json:"entry_price"`
	ExitPrice  float64   `json:"exit_price"`
	Quantity   float64   `json:"quantity"`
	EntryValue float64   `json:"entry_value"`
	ExitValue  float64   `json:"exit_value"`
	PnL        float64   `json:"pnl"`
	ReturnPct  float64   `json:"return_pct"`
}

// BacktestResult is the output of a backtest run.
type BacktestResult struct {
	Symbol           string        `json:"symbol"`
	EquityCurve      []EquityPoint `json:"equity_curve"`
	Trades           []Trade       `json:"trades,omitempty"`
	FinalEquity      float64       `json:"final_equity"`
	TotalReturn      float64       `json:"total_return"`
	AnnualizedReturn float64       `json:"annualized_return"`
	Sharpe           float64       `json:"sharpe"`
	Sortino          float64       `json:"sortino"`
	Calmar           float64       `json:"calmar"`
	MaxDrawdown      float64       `json:"max_drawdown"`
	NumTrades        int           `json:"num_trades"`
	ProfitFactor     float64       `json:"profit_factor"`
	WinRate          float64       `json:"win_rate"`
	AverageWin       float64       `json:"average_win"`
	AverageLoss      float64       `json:"average_loss"`
	AverageTrade     float64       `json:"average_trade"`
	ExposurePercent  float64       `json:"exposure_percent"`
	Turnover         float64       `json:"turnover"`
	FeesPaid         float64       `json:"fees_paid"`
	SlippageCost     float64       `json:"slippage_cost"`
}
